"""add telegram ingress outbox

Revision ID: 9a3c012bd7ef
Revises: 7b4a901f26c3
Create Date: 2026-10-05 23:19:10.307175

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "9a3c012bd7ef"
down_revision = "7b4a901f26c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_bot_webhooks",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("encrypted_secret", sa.Text(), nullable=False),
        sa.Column("secret_digest", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "state", sa.String(length=32), server_default="configuring", nullable=False
        ),
        sa.Column("claim_id", sa.UUID(), nullable=True),
        sa.Column("claim_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('configuring','configured','failed','unknown')",
            name="ck_telegram_webhook_state",
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["telegram_bots.id"],
        ),
        sa.PrimaryKeyConstraint("bot_id"),
    )
    op.create_index(
        op.f("ix_telegram_bot_webhooks_tenant_id"),
        "telegram_bot_webhooks",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "telegram_ingress_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('accepted','ignored')", name="ck_telegram_ingress_state"
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["telegram_bots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bot_id", "update_id", name="uq_telegram_ingress_bot_update"
        ),
    )
    op.create_index(
        "ix_telegram_ingress_scope_id",
        "telegram_ingress_events",
        ["tenant_id", "bot_id", "id"],
        unique=False,
    )
    op.create_table(
        "platform_ingress_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ingress_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column(
            "state", sa.String(length=32), server_default="pending", nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claim_id", sa.UUID(), nullable=True),
        sa.Column("claim_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_job_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('pending','processing','published','failed','cancelled')",
            name="ck_platform_outbox_state",
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= 100", name="ck_platform_outbox_attempts"
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["telegram_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingress_id"],
            ["telegram_ingress_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ingress_id", name="uq_platform_outbox_ingress"),
    )
    op.create_index(
        "ix_platform_outbox_due",
        "platform_ingress_outbox",
        ["state", "next_attempt_at", "claim_deadline"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_platform_outbox_due", table_name="platform_ingress_outbox")
    op.drop_table("platform_ingress_outbox")
    op.drop_index("ix_telegram_ingress_scope_id", table_name="telegram_ingress_events")
    op.drop_table("telegram_ingress_events")
    op.drop_index(
        op.f("ix_telegram_bot_webhooks_tenant_id"), table_name="telegram_bot_webhooks"
    )
    op.drop_table("telegram_bot_webhooks")
    # ### end Alembic commands ###
