"""add source secret

Revision ID: e6e39a93b58d
Revises: 3cd0dbb0eef9
Create Date: 2026-03-18 14:38:59.695764

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = 'e6e39a93b58d'
down_revision = '3cd0dbb0eef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'secret')
    # ### end Alembic commands ###

